### ISSUE TITLE
'Copy URL to clipboard' returns s3 link as opposed to presigned s3 url

### ISSUE THREAD

**Issue by Tehsurfer** [nih-sparc/sparc-app#297]
![image](https://user-images.githubusercontent.com/37255664/119067300-dab10780-ba35-11eb-8bfe-b72c41b6443e.png)
Clicking 'Copy URL to clipboard' returns s3 link:

s3://pennsieve-prod-discover-publish-use1/143/1/files/dataset_description.xlsx

This can be recreated by going to a dataset details page and clicking 'Copy URL to clipboard'
https://sparc.science/datasets/143?type=dataset

**Comment by jwagenaar** [comment]
I think this is expected behavior or at least developed as such intentionally.
