### ISSUE TITLE
SVG icons sometimes do not show

### ISSUE THREAD

**Issue by Tehsurfer** [nih-sparc/sparc-app#311]
Very hard to reproduce, but sometimes no icons load on the site while everything else works fine.

I've seen it happen on sparc.science and staging.sparc.science

Have not been able to catch any errors in the console but will update if I can 

![image](https://user-images.githubusercontent.com/37255664/126579979-e6b6b313-53cf-4260-9bfd-0a5b59416204.png)

**Comment by nickerso** [comment]
I have also seen this behaviour.

**Comment by alan-wu** [comment]
This should now be fixed with #386 .
